ALTER TABLE "Quote"
ADD COLUMN "globalDiscountPercent" DECIMAL(5, 2) NOT NULL DEFAULT 0,
ADD COLUMN "globalDiscountAmount" DECIMAL(12, 2) NOT NULL DEFAULT 0;

ALTER TABLE "QuoteLine"
ADD COLUMN "discountType" TEXT NOT NULL DEFAULT 'PERCENTAGE',
ADD COLUMN "discountAmount" DECIMAL(12, 2) NOT NULL DEFAULT 0;
